# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ada3bcfa76c30661401ca4ef93527033846be7a5fb71b74433e5f57fb34dc09412314c1a69bf84d7bbb3231cd6339f6bbb5d1608ae976c55c61de9c0eff25fda

test:
  secret_key_base: 63a62e183992b95c7b063bab54f0c15deb5650de53eaeb3673c999a5cc0701560bd636375b9d5689e9a2e9097a8140185c282813c853cbbbbc84166cdbe924ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
